repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        always_run: true
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        always_run: true
        pass_filenames: false

      - id: cargo-audit
        name: cargo audit
        entry: cargo audit
        language: system
        types: [rust]
        always_run: true
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        entry: cargo check --all-targets --all-features
        language: system
        types: [rust]
        always_run: true
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        entry: cargo test --all-targets --all-features --no-run
        language: system
        types: [rust]
        always_run: true
        pass_filenames: false
