[build]
rustflags = ["-D", "warnings", "-C", "link-arg=-fuse-ld=mold", "-C", "target-cpu=native",]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-Zshare-generics=y",
]

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"
